py-trading-bot/orders/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb  6 16:31:34 2022

@author: maxime
"""

from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [ 
    path('portfolio/', views.pf_view, name="portfolio"),
    ]

py-trading-bot/reporting/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 29 15:23:49 2022

@author: maxime
"""

from django.urls import path
from reporting import views

app_name = 'reporting'

urlpatterns = [ 
    path('', views.reportsView, name="home"),
    path('alerts/', views.alertsView, name="alerts"),
    path('reports/', views.reportsView, name="reports"),
    path('reports/<int:pk>', views.reportView, name='rep'),
    path('reports_trend/<int:pk>', views.trendView, name='trend'),
    path('start_bot/', views.start_bot, name="start_bot"),
    path('test/', views.test),
    path('trigger_report/<str:exchange>/', views.daily_report,name="report"),
    path('cleaning/', views.cleaning,name="cleaning"),
    path('test_order/', views.test_order,name="test_order"),
    path('actualize_ss/',views.actualize_ss_view, name="actualize_ss"),
    path('create_ss/',views.create_ss),
    path('actualize_all_jobs',views.trigger_all_jobs),
    path('scan/',views.scan)
    ]

py-trading-bot/trading_bot/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reporting.urls')),
    path('', include('orders.urls')),
]

py-trading-bot/reporting/models.py
from django.db import models

import math

from trading_bot.settings import _settings

from core.caller import name_to_ust_or_presel
from core import indicators as ic
import warnings
import logging
logger = logging.getLogger(__name__)
logger_trade = logging.getLogger('trade')

from orders.models import Action, get_exchange_actions, StockEx,  ActionSector,\
                          check_ib_permission, filter_intro_action
from orders.ss_manager import StockStatusManager

class OrderExecutionMsg(models.Model):
    """
    Temporary storage for the telegram to message the orders at the end of the reporting.
    Difficulty is that the telegram bot is async, so it is not possible to just make send_msg() in the order execution function
  
    Attributes
   	----------
         report: Report that generated this list.
         action: stock traded
         text: free text to be displayed in the Telegram message    
    """
    report=models.ForeignKey('Report',on_delete=models.CASCADE)
    action=models.ForeignKey('orders.Action',on_delete=models.CASCADE)
    text=models.TextField(blank=True)

    def concat(self,text):
        print(text)     
        self.text+=text +"\n"
        self.save() 
        
class Report(models.Model):
    """
    Periodically, a report is written. It performs calculation to decide if products need to be bought or sold.
    It also fill ActionReports which saves human readable indicators
    
    Note: a report can cover only one stock exchange.
    
    Attributes
   	----------
         date: Date when the report was generated
         text: free text to be displayed in the Telegram message and in the report 
         stock_ex: corresponding stock exchange
         it_is_index: are the products covered by the report indexes?
         sector: sector of the products covered by the report
    """
    date=models.DateTimeField(null=False, blank=False, auto_now_add=True)   #) default=timezone.now()
    text=models.TextField(blank=True)
    stock_ex=models.ForeignKey('orders.StockEx',on_delete=models.CASCADE,null=True)
    it_is_index=models.BooleanField(blank=False,default=False)
    sector=models.ForeignKey('orders.ActionSector',on_delete=models.CASCADE,blank=True,null=True)
    target_ss_by_st=models.TextField(blank=True,null=True)
    
    def __str__(self):
        return str(self.date)
    
    class Meta:
        ordering = ['-date', 'stock_ex']
        
    def save(self, *args, testing:bool=False,**kwargs):
        '''
        Save the model
        
        Arguments
       	----------
           testing: set to True to perform unittest on the function
        '''
        if "ss_m" not in self.__dir__():
            if self.stock_ex is None:
                self.ss_m=StockStatusManager(self,None,testing=testing)
            else:
                self.ss_m=StockStatusManager(self,self.stock_ex.name,testing=testing)
        super().save(*args, **kwargs)  
            
    def concat(self,text: str):
        '''
        Add text to the report
        
        Arguments
       	----------
           text: text to be added to the report
        '''
        print(text)     
        self.text+=text +"\n"
        self.save()

    def handle_OrderExecutionMsg(
            self, 
            action: Action, 
            used_api: str, 
            buy: bool, 
            strategy: str,
            ):
        '''
        Create a list of action and edit it after an order
        
        Arguments
       	----------
           action: stock where an order was performed
           used_api: API used to perform the trade
           buy: was the order a buy order
           auto: was the order automatic or not
           strategy: name of the strategy which decided of this order        
        '''
        buy_sell_txt={True:"buying ", False: "selling "}
        if used_api!="YF":
            txt=buy_sell_txt[buy].capitalize()+"order executed, symbol: " +action.symbol +" strategy: " + strategy
        else:
            txt="Manual " + buy_sell_txt[buy].lower()+"order request, symbol: " +action.symbol +" strategy: " + strategy
        logger_trade.info(txt)
        OrderExecutionMsg.objects.create(
            report=self,
            action=action,
            text=txt
            )

### Preselected actions strategy    
    def perform_sub(
            self,
            strats,
            ust, 
            exchange: str,
            it_is_index:bool=False,
            sec:str=None
            ):
        '''
        Sub-function for perform_sub
        '''
        try:
            for st in strats:
                if st.class_name is None and st.ml_model_name is None:
                    print("define class_name or ml_model_name for strategy "+str(st.name))
                else:
                    ust_or_pr=name_to_ust_or_presel(
                        st.class_name,
                        st.ml_model_name,
                        ust.period,
                        input_ust=ust,
                        prd=True,
                        it_is_index=it_is_index,
                        st=st
                        )  
                    if ust_or_pr is not None: #presel with it_is_index
                        if st.class_name in ["PreselRetard","PreselRetardMacro"]:
                            keep=False
                            for st1 in strats: #if retard_keep is also active, keep.
                                if st1.name=="retard_keep":
                                    keep=True
                            ust_or_pr.perform(self, keep=keep)
                        else:
                            ust_or_pr.perform(self)
                    
        except Exception as e:
              import sys
              _, e_, exc_tb = sys.exc_info()
              print(e)
              print("line " + str(exc_tb.tb_lineno) + " for strategy: "+str(st.name))
              logger.info("line " + str(exc_tb.tb_lineno), stack_info=True, exc_info=True)
              logger.error("line " + str(exc_tb.tb_lineno), stack_info=True, exc_info=True)
      
    def perform(
            self,
            ust,
            sec:str=None,
            intraday:bool=False,
            it_is_index:bool=False,
            ):
        '''
        Perform all strategies and there related trades for a given set of symbols
        
        Arguments
       	----------
          ust: underlying strategy
          sec: sector of the stocks for which we write the report
          intraday: is it a report at the end of the day or during it
          it_is_index: is it indexes that are provided 
        '''
        try:
            if ust.exchange is None: #for indexes
                stock_exs=[a.stock_ex for a in ust.actions]
            else:
                stock_exs=[StockEx.objects.get(name=ust.exchange)]
                
            if intraday:
                a="strategies_in_use_intraday"
            else:
                a="strategies_in_use"
            
            for stock_ex in stock_exs: #sector is already in ust
                strats=getattr(stock_ex,a).all()
                self.perform_sub(strats,ust,ust.exchange,it_is_index=it_is_index)
        except Exception as e:
             import sys
             _, e_, exc_tb = sys.exc_info()
             print(e)
             print("line " + str(exc_tb.tb_lineno))
        
    def populate_report(
            self, 
            symbols: list, 
            symbols_to_YF: dict,
            ust_hold,
            ust_trend,
            ust_kama,
            ust_ma):
        '''
        Fill the report with result of the calculations
        
        Arguments
       	----------
           symbols: list of IB or YF ticker
           ust_hold, ust_trend, ust_kama, ust_ma: underlying strategies containing some calculation results 
           exchange: name of the stock exchange
        '''
        for symbol in symbols:
            if math.isnan(ust_hold.vol[symbol].values[-1]):
                self.concat("symbol " + symbol + " no data")
                
            else:
                with warnings.catch_warnings():
                    #Necessary because of the presence of NaN
                    warnings.simplefilter("ignore", category=RuntimeWarning)
                    
                    ar=ActionReport(
                        action=Action.objects.get(symbol=symbols_to_YF[symbol]), 
                        report=Report.objects.get(pk=self.pk))

                    if ust_trend is not None:
                        grow_past50_raw=ust_trend.grow_past(50, False)
                        grow_past50_ma=ust_trend.grow_past(50, True)
                        grow_past20_raw=ust_trend.grow_past(20, False)
                        grow_past20_ma=ust_trend.grow_past(20, True)
                        ar.vol=ust_trend.vol[symbol].values[-1]

                        symbol_complex_ent=ust_trend.symbols_simple_to_complex(symbol,"ent")
                        
                        ar.bbands_bandwith=ust_trend.bb_bw[symbol_complex_ent].values[-1]
                        ar.trend=float(ust_trend.trend[symbol_complex_ent].values[-1])
                        ar.macro_trend=float(ust_trend.macro_trend[symbol_complex_ent].values[-1])
                    
                    ar.three_mo_evol=grow_past50_raw[(50,False,symbol)].values[-1]
                    ar.three_mo_evol_sm=grow_past50_ma[(50,True,symbol)].values[-1]
                    ar.one_mo_evol=grow_past20_raw[(20,False,symbol)].values[-1]
                    ar.one_mo_evol_sm=grow_past20_ma[(20,True,symbol)].values[-1]
                    
                    ar.kama_ent=ust_kama.entries_kama[symbol].values[-1]
                    ar.kama_ex=ust_kama.exits_kama[symbol].values[-1]
                    ar.kama_dir=float(ust_kama.direction[symbol].values[-1])
            
                    ar.stoch_ent=ust_kama.entries_stoch[symbol].values[-1]

py-trading-bot/reporting/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from reporting.telegram import start, cleaning_sub
# Create your views here.
from reporting.models import Report, ActionReport, Alert, OrderExecutionMsg 
from reporting.scanner import Scanner
from orders.models import Action, StockStatus, exchange_to_index_symbol, ActionSector, StockEx, Job,\
                          get_exchange_actions, Strategy, filter_intro_action
         
from orders.ib import actualize_ss
from core import caller
from .filter import ReportFilter
from django.utils import timezone

def reportsView(request): 
    reports= Report.objects.all()
    context={'reports': ReportFilter(request.GET, queryset=reports)}
    return render(request, 'reporting/reports.html', context)

def reportView(request,pk):
    report= Report.objects.filter(id=pk)
    ars=ActionReport.objects.filter(report=pk)

    context={'report':report[0], 'ars':ars}
    return render(request, 'reporting/report.html', context)
    
def trendView(request,pk): 
    report= Report.objects.filter(id=pk)
    ars=ActionReport.objects.filter(report=pk)
    
    context={'report':report[0], 'ars':ars}
    return render(request, 'reporting/trend.html', context)

def alertsView(request): 
    alerts= Alert.objects.filter(active=True)
    context={'alerts':alerts}
    return render(request, 'reporting/alerts.html', context)

#manual start to avoid multiple instanciation
def start_bot(request):
    start()
    print("bot_start ok")
    return redirect('reporting:reports')

#For testing purpose
def daily_report_sub(
        exchange:str,
        it_is_index:bool=False,
        **kwargs):
    
    if exchange is not None:
        report1=Report.objects.create(stock_ex=StockEx.objects.get(name=exchange))
    else:
        report1=Report.objects.create()
    report1.daily_report(exchange=exchange,it_is_index=it_is_index,**kwargs)
    
    oems=OrderExecutionMsg.objects.filter(report=report1)
    for oem in oems:
        print(oem.text)
    if report1.text:
        print(report1.text)     

def daily_report(
        request,
        exchange:str,
        **kwargs):
    '''
    Write report for an exchange and/or sector
    Identical to the telegrambot function, but here without bot, so sync instead of async
    Either for test purpose, or if your telegram was stopped
    
    Arguments
   	----------
       request: incoming http request
       exchange: name of the stock exchange
    '''  
    s_ex=StockEx.objects.get(name=exchange)
    a="strategies_in_use"
    print("writting daily report "+s_ex.name)
    if s_ex.presel_at_sector_level:
        for sec in ActionSector.objects.all():
            strats=getattr(sec,a).all()
            if len(strats)!=0: #some strategy is activated for this sector
                print("starting report " + sec.name)
                daily_report_sub(s_ex.name,sec=sec)
    else:
        strats=getattr(s_ex,a).all()
        if len(strats)!=0: 
            daily_report_sub(s_ex.name)

    daily_report_sub(exchange=None,symbols=[exchange_to_index_symbol(s_ex.name)[1]],it_is_index=True)
    return render(request, 'reporting/success_report.html')

def cleaning(request):
    '''
    Deactivate the alert at the end of the day
    '''
    cleaning_sub()
        
    return HttpResponse("cleaning done")

def actualize_ss_view(request):
    actualize_ss()
    return HttpResponse("Stock status actualized")

def create_ss_sub():
    for a in Action.objects.all():
        ss, created=StockStatus.objects.get_or_create(action=a)

def create_ss(request):
    create_ss_sub()
    return HttpResponse("Stock status created")

def trigger_all_jobs(request):
    '''
    If you start with the bot, to create the initial slow presel
    '''
    today=timezone.now()
    for j in Job.objects.all():
        actions=get_exchange_actions(j.stock_ex.name)
        actions=filter_intro_action(actions,j.period_year)
        st=Strategy.objects.get(name=j.strategy.name)
        pr=caller.name_to_ust_or_presel(
            st.class_name, 
            None,
            str(j.period_year)+"y",
            prd=True, 
            actions=actions,
            exchange=j.stock_ex.name,
            st=st
            ) 
        pr.actualize()   
        j.last_execution=today
        j.save()
    return HttpResponse("All jobs ran")

def scan(request):
    s=Scanner(restriction=90,fees=0.0005)
    res=s.scan_all()
    print(res)
    return HttpResponse("Scan ran successfully")

def test_order(request):
    symbol=""
    strategy=""
    exchange="XETRA"
    short=False
    return render(request, 'reporting/success_report.html')
    #with MyIB() as myIB:
    #    return myIB.entry_order(symbol,strategy, exchange,short), True
    
    return HttpResponse("test")

def test(request):
    from ib_insync import Stock
    import vectorbtpro as vbt
        
    import logging
    from orders.ib import place
    #logger = logging.getLogger(__name__)
    action=Action.objects.get(symbol="IBM")
    txt, _, _= place(True,
                            action,
                            False,
                            order_size=15000)
    #action=Action.objects.get(symbol="EN.PA")
    #myIB=MyIB()
    
    #contract = Stock(action.ib_ticker,action.stock_ex.ib_ticker, action.currency.symbol)
    #myIB.get_past_closing_price(contract)
    #cours_open, cours_close, cours_low, cours_high=retrieve_data(["EN.PA","DG.PA"],"1y")
    #macd=vbt.MACD.run(cours_close)
    #print(macd.macd)
    #print(myIB.positions())
    
    
    #check_hold_duration("KER.PA",False,key="retard")
    #report=Report(ent_symbols=[],ex_symbols=[])
    #report.save()
    #report.daily_report_17h()
    
    #
    #myIB.test("OR.PA")
    #myIB.entry_order("OR.PA",False,strat19=True)
    #myIB.exit_order("OR.PA",False,strat19=True)
    #print(myIB.ib.accountSummary())
    #print(myIB.ib.accountValues())
    #print(myIB.ib.positions())

    #retrieve('AAPL',"10 D")    
    #myIB.disconnect()
    
    return HttpResponse("test ok")

py-trading-bot/reporting/templates/reporting/alerts.html
<h1>Alerts</h1>
{% if alerts %}
<table>
    <thead>
        <tr>
            <th>Action</th>
            <th>Short</th>
            <th>Alarm</th>
            <th>Triggering</th>
        </tr>
    </thead>
     {% for alert in alerts %}
    <tr>
        <td>{{alert.action.name}}</td>
        <td>{{alert.short}}</td>
        <td>{{alert.alarm}}</td>
        <td>{{alert.trigger_date}}</td>
    </tr>
    {% endfor %}
</table>      

{% else %}
<p>No alert active</p>
{% endif %}
<p><a href="{% url 'reporting:reports' %}">Main page</a></p>

py-trading-bot/reporting/templates/reporting/report.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'reporting/report.css' %}">
{% if report %}

{% if report.it_is_index %}
    <h1>Daily trend report {{report.date}}</h1>
{% else %}
    {% if report.sector == "undefined" %}
    <h1>Daily trend report {{report.stock_ex}} {{report.date}}</h1>
    {% else %}
    <h1>Daily trend report {{report.stock_ex}} {{report.date}}, sector {{report.sector}}</h1>
    {% endif %}
{% endif %}

<p>{{report.text|linebreaks }}</p>

<h1>Stocks list</h1>
    <table>
        <thead>
            <tr>
                <th>Stock</th>
                <th>Symbol</th>
                <th>Kama, ent</th>
                <th>Kama, ex</th>
                <th>Stoch, ent</th>
                <th>Stoch, ex</th>   
                <th>Stoch</th>  
                <th>Ma, ent</th>
                <th>Ma, ex</th>            

            </tr>
        </thead>
         {% for ar in ars %}
        <tr>
            <td>{{ar.action.name}}{{ar.index.name}}</td>
            <td>{{ar.action.symbol}}{{ar.index.symbol}}</td>

            {% if ar.kama_ent %}
                <td class="true">{{ar.kama_ent}}</td>
            {% else %}
                <td class="false">{{ar.kama_ent}}</td>
            {% endif %}

            {% if ar.kama_ex %}
                <td class="exit">{{ar.kama_ex}}</td> 
            {% else %}
                <td class="false">{{ar.kama_ex}}</td> 
            {% endif %}
                
            {% if ar.stoch_ent %}
                <td class="true">{{ar.stoch_ent}}</td> 
            {% else %}
                <td class="false">{{ar.stoch_ent}}</td> 
            {% endif %}
             
            {% if ar.stoch_ex %}
                <td class="exit">{{ar.stoch_ex}}</td> 
            {% else %}
                <td class="false">{{ar.stoch_ex}}</td> 
            {% endif %}
            
            <td>{{ar.stoch|floatformat:2 }}</td> 
            
            {% if ar.ma_ent %}
                <td class="true">{{ar.ma_ent}}</td> 
            {% else %}
                <td class="false">{{ar.ma_ent}}</td> 
            {% endif %}                         

             {% if ar.ma_ex %}
                 <td class="exit">{{ar.ma_ex}}</td> 
             {% else %}
                 <td class="false">{{ar.ma_ex}}</td> 
             {% endif %}           
        </tr>
        {% endfor %}
    </table>      

{% else %}
<p>No report found</p>
{% endif %}
<h2>Legend</h2>
<p>Pattern light uses some patterns to determine entries (ent) and exits (ex) signals</p>
<p>KAMA extrema can be used for the same purposed. So the price curve is smoothed with KAMA and we look for extrema.</p>
<p>STOCH is the corresponding function. When it crosses 20, it is an entries signal, 80 an exit one here.</p>
<p>MA is coded the following way. If the smoothed (MA) price over 5 days cross the one over 15 days, a signal is produced.
Entries if the fast signal becomes greater than the slow one and exits if it is the opposite.</p>

<h1>Target quantity by strategy</h1>
<p>1 means that we want to have the product in long, -1 the product in short, 0 no product. NaN means no decision is taken by this strategy<br/>
The columns are the different strategies</p>
<p>{{report.target_ss_by_st|linebreaks }}</p>

<p><a href="{% url 'reporting:reports' %}">Main page</a></p>

py-trading-bot/reporting/templates/reporting/reports.html
<h1>Python Trading bot</h1>
<p><b>Author: Psemdel, Version: 0.30, <a href="https://github.com/psemdel/py-trading-bot">Github</a></b></p>
<table>
    <tr>
        <td><a href="{% url 'reporting:start_bot' %}">Start bot</a></td>
    </tr>
    <tr>
        <td><a href="{% url 'orders:portfolio' %}">Portfolio</a></td>
        <td><a href="{% url 'reporting:alerts' %}">Alerts</a></td>
    </tr>
    <tr>
        <td><a href="{% url 'reporting:report' 'Paris' %}">Write report for Paris</a></td>
        <td><a href="{% url 'reporting:report' 'XETRA' %}">Write report for Xetra</a></td>
    </tr>
    <tr>    
        <td><a href="{% url 'reporting:report' 'Nasdaq' %}">Write report for Nasdaq</a></td>
        <td><a href="{% url 'reporting:report' 'NYSE' %}">Write report for NYSE</a></td>
    </tr>
    <tr>
        <td><a href="{% url 'reporting:cleaning' %}">Cleaning alerts</a></td>
        <td><a href="{% url 'admin:index' %}">Admin panel</a></td>
    </tr>
</table>
<br/>
<h1>Reports</h1>
<form method="get">
  <table style="background-color:00CED1;">
      <th >
          <td width="20%">
               Start date {{ reports.form.start_date  }}
          </td>
          <td width="20%">
               End date {{ reports.form.end_date  }}
          </td>          
          <td width="20%">
               Stock exchange {{ reports.form.stock_ex }}
          </td>     
          <td width="20%">
               Index only {{ reports.form.it_is_index }}
          </td> 
          <td>
               <button type="submit">Filter</button>
          </td>
      </th>  
  </table>
</form>

<table>
    {% for report in reports.qs %}
        {% if report.it_is_index %}
        <tr>
            {% if report.sector == "undefined" %}
            <td><a href="{% url 'reporting:rep' report.id %}">Decision index {{ report.date }}</a></td>
            <td><a href="{% url 'reporting:trend' report.id %}">Trend index {{ report.date }}</a></td>
            {% else %}
            <td><a href="{% url 'reporting:rep' report.id %}">Decision index {{ report.date }} {{report.sector}}</a></td>
            <td><a href="{% url 'reporting:trend' report.id %}">Trend index {{ report.date }} {{report.sector}}</a></td>
            {% endif %}
        </tr>
        {% else %}
        <tr>
            {% if report.sector == "undefined" %}
            <td><a href="{% url 'reporting:rep' report.id %}">Decision {{report.stock_ex}} {{ report.date }}</a></td>
            <td><a href="{% url 'reporting:trend' report.id %}">Trend {{report.stock_ex}} {{ report.date }}</a></td>
            {% else %}
            <td><a href="{% url 'reporting:rep' report.id %}">Decision {{report.stock_ex}} {{ report.date }} {{report.sector}}</a></td>
            <td><a href="{% url 'reporting:trend' report.id %}">Trend {{report.stock_ex}} {{ report.date }} {{report.sector}}</a></td>
            {% endif %}
        </tr>
        {% endif %}
    {% endfor %}
</table>

py-trading-bot/reporting/templates/reporting/success_report.html
<p>report written, <a href="{% url 'reporting:reports' %}">Main page</a></p>